language: node_js
sudo: required
cache:
    npm: false
node_js:
- lts/*
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: xR8HDjpnnX/O6ekhbRehaK8LOf0eWkn1IKzxI/OjJHKP1c7QpT3sCmNiewDrnZXHDhXK0o8+ixVB0k6K8tBOoqb3mFtXLMczCx7EhgqUgmp+J42PpSffS81knMzN7COJXWfkbxnwCcsah348/8TkWUx4WDn7iSC7XfBGZXoftpoOwcySRZ2yucmai6cNdOtao9oV9MliufHdOdZ5lOaDArZWu10Mmm4aiHRHuJbcmCsOEusO3TOjPC5D4gKh2Qt6RvV/syVju50vvbYdcKyD6xKsIaX5wGzZNzZmIjq+TjbAXYkMk5cfYXsnUiSnlZSWPF/DSOuM+CON5eQQgucQHQQCqVBeiRWICRth+2xfrEkqze3/wtx24wi4xPK+G+DHO2ur1lJGXqgjWeg/07v40lPRM3p2MIcz6Lh5wK/ZOWdttnOyplMlB4J7CHpPK9HaC/MxMDtsWoUlJzyzpKyRaUxPAMpkRznUmDwxGlJNEKmvVI46tCqSHpCatZIX0CeL2ptwSRDWadllrwvlcRgvZLkQjExF/SCgFgwO/9TV93MK/KJrM1iRsJ7qluUSvrmRVO9APf5iXqKqU21ZCDXGaS4HoS0cGxgDO2n6e4Xo1lK3xlosncoiuTkCJcn+eMqnqBn9lK/H9mFtPLnF+/yDJ5ID4S4pqbaUWCarR3YhCE8=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - dbus
    - gcc-4.8
    - g++-4.8
    - libglib2.0-dev
before_script:
- npm install -g node-gyp
- npm install -g grunt-cli npm
- npm install -g p3x-onenote
